### PR TITLE
rpi3-resizerootfs: Support non mmc devices for initial resize

### PR DESCRIPTION
**Pull request by nicman23**

### CODE REVIEW

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
Before I merge, can you update the commit message from “update rpi3-resizerootfs” to something conveying the intention behind the change please? E.g. “support all kinds of storage (e.g. USB)”.

**Comment by nicman23** [comment]
done

**Comment by stapelberg** [comment]
You changed the pull request title. Please change the commit message, too, as that’s what ends up in the git history (and hence in “git blame” output, for example).

**Review by nicman23 — COMMENTED** [review]
Resize script does not work for usb storage

**Comment by nicman23** [comment]
sorry, fixed, i do not use github ui that much

**Comment by stapelberg** [comment]
On https://github.com/Debian/raspi3-image-spec/pull/16/commits, I still see the old commit message.

If you prefer the command-line, see “view command line instructions”, then use `git commit --amend` (or interactive rebase) and force-push afterwards.

Or, if it’s easier, you can also create a new pull request altogether :)

**Comment by jlu5** [comment]
(If it helps speed this up, GitHub lets you squash+merge and override the commit message if enabled in repository settings: https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-on-github)

**Comment by gwolf** [comment]
I am closing this pull request as we will most probably use the rewritten resizerootfs script instead.

**Pull request closed without merging**
