### PR TITLE
Install linux-image-4.18-rc from experimental to support RPi 3B+

### PR DESCRIPTION
**Pull request by chschlue**

### CODE REVIEW

**Comment by gwolf** [comment]
This is not needed TTBOMK. Maybe something migrated to testing since this pull request was made, don't know, but I have successfully worked with several 3B+ machines without this. I prefer not to install from experimental (or, for that matter, from anything outside testing) if it can be avoided.

**Comment by chschlue** [comment]
See issue #12 
Especially, 4.18-rc fixes ethernet.

I get your point, I just think having working ethernet would be nice before 4.18 hits testing in September or so.

**Comment by guhahn** [comment]
I've built my own image and only added following lines in raspi3.yaml:
after line 63:
`echo 'deb http://deb.debian.org/debian experimental main contrib non-free' >> /etc/apt/sources.list`

after line 66 of actual raspi3.yaml I've added a line with the actual linux image from experimental:
`- linux-image-4.18.0-rc5-arm64-unsigned`

After this, it works fine with my 3B+

**Comment by chschlue** [comment]
Yes, that's exactly what this PR was about.

**Pull request closed without merging**
