### PR TITLE
Add filesystem labels

### PR DESCRIPTION
**Pull request by chschlue**
Update vmdb2 submodule to current version.
Add fs labels to raspi3.yaml.
Mount /root and /boot by label.

Squashes bug #17

### CODE REVIEW

**Comment by gwolf** [comment]
Cannot merge this request, but I am adding the changes via two commits (8f0b6f3 for the vmdb2 repository location, 11943e5 for mounting by label - I have not yet pushed this last one, I'm doing a test build right now). Thanks!

**Comment by chschlue** [comment]
I could rebase the PR if it helps to a cleaner history.

**Comment by gwolf** [comment]
Christian Schlüter dijo [Tue, Aug 14, 2018 at 08:01:18PM +0000]:
> I could rebase the PR if it helps to a cleaner history.

It's done with different commits - But I still want to check some
things. It's missing a couple of spots, such as the cmdline.txt line,
that does not allow for a clean boot from non-MMC media.

Also, there is one last thing I want to do before pushing out a new
release: Prepare and upload a new raspberry3-firmware image, so that
the wireless card is supported (see issue #12).

**Comment by chschlue** [comment]
Guess I should have mentioned [Debian bug 903543](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903543). My bad.

**Pull request closed without merging**
